version: '3.8'

services:
  dev.app:
    image: patientor.dev.backend
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: dev.backend
    ports:
      - 4000:4000
    volumes:
      - ./:/usr/src/app
    environment:
      - MONGO_URL=mongodb://the_username:the_password@dev.mongo:27017/the_database
      - REDIS_URL=redis://dev.redis:6379
      - NODE_ENV=development
    depends_on:
      dev.mongo:
        condition: service_started
  dev.mongo:
    image: mongo
    container_name: dev.mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongo_data_dev:/data/db
  dev.redis:
    image: redis
    container_name: dev.redis
    command: ['redis-server', '--appendonly', 'yes'] # Overwrite the CMD
    volumes:
      - ./redis_data_dev:/data
  dev.debug-helper:
    image: busybox
    container_name: dev.debug-helper
